package com.papertrade.service;

import com.papertrade.domain.User;
import com.papertrade.dto.AuthResponse;
import com.papertrade.dto.LoginRequest;
import com.papertrade.dto.RegisterRequest;
import com.papertrade.exception.DuplicateUserException;
import com.papertrade.exception.InvalidCredentialsException;
import com.papertrade.repository.UserRepository;
import com.papertrade.security.JwtService;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.JwtException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Mono;

import java.util.UUID;

/**
 * Authentication service: registration, login, and token refresh.
 *
 * On registration a User is created (with a BCrypt-hashed password) and a
 * trading account is provisioned via {@link AccountService}. Passwords are
 * never stored or compared in plaintext.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class AuthService {

    private final UserRepository userRepository;
    private final AccountService accountService;
    private final PasswordEncoder passwordEncoder;
    private final JwtService jwtService;

    /**
     * Register a new user, provision their trading account, and issue tokens.
     */
    public Mono<AuthResponse> register(RegisterRequest request) {
        String username = request.getUsername().trim();
        String email = request.getEmail().trim().toLowerCase();

        return userRepository.existsByUsername(username)
            .flatMap(usernameTaken -> usernameTaken
                ? Mono.error(new DuplicateUserException("Username already taken"))
                : userRepository.existsByEmail(email))
            .flatMap(emailTaken -> {
                if (Boolean.TRUE.equals(emailTaken)) {
                    return Mono.error(new DuplicateUserException("Email already registered"));
                }

                User user = User.builder()
                    // userId generated by the database (INSERT on null @Id)
                    .username(username)
                    .email(email)
                    .hashedPassword(passwordEncoder.encode(request.getPassword()))
                    .enabled(true)
                    .build();

                // createAccount saves the user and provisions the $100k account
                return accountService.createAccount(user)
                    .flatMap(account -> userRepository.findByUsername(username))
                    .map(this::toAuthResponse);
            });
    }

    /**
     * Authenticate a user and issue tokens.
     */
    public Mono<AuthResponse> login(LoginRequest request) {
        return userRepository.findByUsername(request.getUsername().trim())
            .filter(user -> passwordEncoder.matches(request.getPassword(), user.getHashedPassword()))
            .map(this::toAuthResponse)
            .switchIfEmpty(Mono.error(new InvalidCredentialsException("Invalid username or password")));
    }

    /**
     * Exchange a valid refresh token for a new pair of tokens.
     */
    public Mono<AuthResponse> refresh(String refreshToken) {
        return Mono.fromCallable(() -> jwtService.parse(refreshToken))
            .onErrorMap(JwtException.class,
                e -> new InvalidCredentialsException("Invalid or expired refresh token"))
            .flatMap(claims -> {
                if (!jwtService.isRefreshToken(claims)) {
                    return Mono.error(new InvalidCredentialsException("Not a refresh token"));
                }
                UUID userId = UUID.fromString(claims.getSubject());
                return userRepository.findById(userId)
                    .map(this::toAuthResponse)
                    .switchIfEmpty(Mono.error(new InvalidCredentialsException("User no longer exists")));
            });
    }

    private AuthResponse toAuthResponse(User user) {
        return AuthResponse.builder()
            .accessToken(jwtService.generateAccessToken(user.getUserId(), user.getUsername()))
            .refreshToken(jwtService.generateRefreshToken(user.getUserId(), user.getUsername()))
            .userId(user.getUserId())
            .username(user.getUsername())
            .build();
    }
}
