package com.papertrade.service;

import com.papertrade.domain.Notification;
import com.papertrade.repository.NotificationRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.UUID;

@Slf4j
@Service
@RequiredArgsConstructor
public class NotificationService {

    private final NotificationRepository notificationRepository;

    public Mono<Notification> create(UUID userId, String type, String message) {
        Notification notification = Notification.builder()
            // notificationId generated by the database (INSERT on null @Id)
            .userId(userId)
            .type(type)
            .message(message)
            .isRead(false)
            .build();
        return notificationRepository.save(notification);
    }

    public Flux<Notification> list(UUID userId) {
        return notificationRepository.findByUserIdOrderByCreatedAtDesc(userId);
    }

    public Mono<Long> unreadCount(UUID userId) {
        return notificationRepository.countByUserIdAndIsReadFalse(userId);
    }

    public Mono<Void> markAllRead(UUID userId) {
        return notificationRepository.markAllRead(userId);
    }
}
