package com.papertrade.service;

import com.papertrade.domain.PortfolioSnapshot;
import com.papertrade.domain.TradingAccount;
import com.papertrade.dto.SnapshotPoint;
import com.papertrade.repository.AccountRepository;
import com.papertrade.repository.PortfolioSnapshotRepository;
import com.papertrade.repository.PositionRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Records periodic portfolio-value snapshots and serves them for the chart.
 *
 * A scheduled job values every account at live prices and stores a row, so the
 * dashboard chart reflects real growth over time (historical value can't be
 * recomputed from today's prices - it must be captured as it happens).
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class PortfolioSnapshotService {

    private final AccountRepository accountRepository;
    private final PositionRepository positionRepository;
    private final PortfolioSnapshotRepository snapshotRepository;
    private final MarketDataService marketDataService;

    /**
     * Scheduled capture of all accounts' portfolio values.
     * Interval/initial delay configurable via snapshot.* properties.
     */
    @Scheduled(
        initialDelayString = "${snapshot.initial-delay-ms:15000}",
        fixedDelayString = "${snapshot.interval-ms:60000}")
    public void scheduledCapture() {
        captureAll()
            .subscribe(
                count -> log.debug("Captured {} portfolio snapshot(s)", count),
                error -> log.error("Snapshot capture failed: {}", error.getMessage()));
    }

    /**
     * Value every account and persist a snapshot for each.
     */
    public Mono<Long> captureAll() {
        return accountRepository.findAll()
            .flatMap(this::captureForAccount)
            .count();
    }

    private Mono<PortfolioSnapshot> captureForAccount(TradingAccount account) {
        return positionRepository.findByAccountId(account.getAccountId())
            .flatMap(position ->
                marketDataService.getCurrentPrice(position.getSymbol())
                    // Fall back to the last cached price if the quote lookup fails,
                    // so one bad symbol doesn't sink the whole snapshot.
                    .onErrorReturn(position.getCurrentPrice() != null
                        ? position.getCurrentPrice()
                        : BigDecimal.ZERO)
                    .map(price -> price.multiply(position.getQuantity())))
            .reduce(BigDecimal.ZERO, BigDecimal::add)
            .map(positionValue -> {
                BigDecimal cash = account.getBalance();
                BigDecimal positions = positionValue.setScale(2, RoundingMode.HALF_UP);
                return PortfolioSnapshot.builder()
                    // snapshotId generated by the database (INSERT on null @Id)
                    .accountId(account.getAccountId())
                    .cashBalance(cash)
                    .positionValue(positions)
                    .totalValue(cash.add(positions).setScale(2, RoundingMode.HALF_UP))
                    .capturedAt(LocalDateTime.now())
                    .build();
            })
            .flatMap(snapshotRepository::save);
    }

    /**
     * Portfolio-value history for the authenticated user's account (oldest first).
     */
    public Flux<SnapshotPoint> getHistory(UUID userId) {
        return accountRepository.findByUserId(userId)
            .flatMapMany(account ->
                snapshotRepository.findByAccountIdOrderByCapturedAtAsc(account.getAccountId()))
            .map(s -> new SnapshotPoint(s.getCapturedAt().toString(), s.getTotalValue()));
    }
}
