package com.papertrade.service;

import com.papertrade.domain.WatchlistItem;
import com.papertrade.domain.enums.AlertDirection;
import com.papertrade.repository.WatchlistRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.math.BigDecimal;
import java.util.UUID;

/**
 * Watchlist management + price-alert evaluation.
 *
 * Alerts are directional: at creation the target is compared to the live price
 * to decide whether it's an ABOVE or BELOW alert, so "notify me at $X" works
 * whether X is above or below the current price. Each alert fires once.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class WatchlistService {

    private final WatchlistRepository watchlistRepository;
    private final NotificationService notificationService;
    private final MarketDataService marketDataService;

    public Flux<WatchlistItem> list(UUID userId) {
        return watchlistRepository.findByUserIdOrderByCreatedAtDesc(userId);
    }

    /**
     * Add or update a watchlist entry. If an alertPrice is given, its direction
     * is derived from the current price.
     */
    public Mono<WatchlistItem> addOrUpdate(UUID userId, String symbol, BigDecimal alertPrice) {
        String upper = symbol.toUpperCase();

        // No alert price -> plain watch entry, no direction, no price lookup.
        if (alertPrice == null) {
            return upsert(userId, upper, null, null);
        }

        // Direction is derived from the current price so "notify me at $X" works
        // whether X is above or below where the stock trades right now.
        return marketDataService.getCurrentPrice(upper)
            .map(current -> alertPrice.compareTo(current) >= 0
                ? AlertDirection.ABOVE : AlertDirection.BELOW)
            .onErrorReturn(AlertDirection.ABOVE)
            .flatMap(dir -> upsert(userId, upper, alertPrice, dir));
    }

    private Mono<WatchlistItem> upsert(UUID userId, String symbol,
                                       BigDecimal alertPrice, AlertDirection direction) {
        return watchlistRepository.findByUserIdAndSymbol(userId, symbol)
            .flatMap(existing -> {
                existing.setAlertPrice(alertPrice);
                existing.setAlertDirection(direction);
                existing.setTriggered(false); // re-arm on update
                return watchlistRepository.save(existing);
            })
            .switchIfEmpty(Mono.defer(() -> watchlistRepository.save(
                WatchlistItem.builder()
                    // watchlistId generated by the database (INSERT on null @Id)
                    .userId(userId)
                    .symbol(symbol)
                    .alertPrice(alertPrice)
                    .alertDirection(direction)
                    .triggered(false)
                    .build())));
    }

    public Mono<Void> remove(UUID userId, String symbol) {
        return watchlistRepository.deleteByUserIdAndSymbol(userId, symbol.toUpperCase());
    }

    /**
     * Evaluate all active alerts for a symbol against a fresh price.
     * Fires a notification (once) for each crossed alert. Called on price ticks.
     */
    public Mono<Void> checkAlerts(String symbol, BigDecimal price) {
        return watchlistRepository
            .findBySymbolAndTriggeredFalseAndAlertPriceIsNotNull(symbol.toUpperCase())
            .filter(item -> isCrossed(item, price))
            .flatMap(item -> {
                item.setTriggered(true);
                String message = String.format("%s hit your alert of $%.2f (now $%.2f)",
                    item.getSymbol(), item.getAlertPrice(), price);
                return notificationService.create(item.getUserId(), "PRICE_ALERT", message)
                    .then(watchlistRepository.save(item));
            })
            .then();
    }

    private boolean isCrossed(WatchlistItem item, BigDecimal price) {
        if (item.getAlertDirection() == AlertDirection.ABOVE) {
            return price.compareTo(item.getAlertPrice()) >= 0;
        }
        return price.compareTo(item.getAlertPrice()) <= 0;
    }
}
